-- DROP TABLE IF EXISTS TB_PERFUME_REVIEW_M;
CREATE TABLE TB_PERFUME_REVIEW_M (
    REVIEW_ID   BIGINT        NOT NULL,          -- 리뷰 고유 ID
    PERFUME_ID  BIGINT        NOT NULL,          -- 향수 ID
    CONTENT     TEXT          NOT NULL,          -- 리뷰 본문
    LOAD_DT     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_TB_PERFUME_REVIEW_M
        PRIMARY KEY (REVIEW_ID),

    CONSTRAINT FK_TB_PERFUME_REVIEW_M_PERFUME
        FOREIGN KEY (PERFUME_ID)
        REFERENCES TB_PERFUME_BASIC_M (PERFUME_ID)
);